// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo"

	mock "github.com/stretchr/testify/mock"

	model "github.com/paraizofelipe/gorecipes/model"
)

// RecipeHandler is an autogenerated mock type for the RecipeHandler type
type RecipeHandler struct {
	mock.Mock
}

// APIRecipeToRecipe provides a mock function with given fields: _a0
func (_m *RecipeHandler) APIRecipeToRecipe(_a0 []model.APIRecipe) ([]model.Recipe, error) {
	ret := _m.Called(_a0)

	var r0 []model.Recipe
	if rf, ok := ret.Get(0).(func([]model.APIRecipe) []model.Recipe); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Recipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]model.APIRecipe) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipes provides a mock function with given fields: _a0
func (_m *RecipeHandler) GetRecipes(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
