// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/paraizofelipe/gorecipes/model"
	mock "github.com/stretchr/testify/mock"
)

// RecipeSearcher is an autogenerated mock type for the RecipeSearcher type
type RecipeSearcher struct {
	mock.Mock
}

// Search provides a mock function with given fields: ingredients
func (_m *RecipeSearcher) Search(ingredients string) (model.APIRecipeResponse, error) {
	ret := _m.Called(ingredients)

	var r0 model.APIRecipeResponse
	if rf, ok := ret.Get(0).(func(string) model.APIRecipeResponse); ok {
		r0 = rf(ingredients)
	} else {
		r0 = ret.Get(0).(model.APIRecipeResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ingredients)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
