// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// MakeRequest provides a mock function with given fields: method, url
func (_m *Requester) MakeRequest(method string, url string) ([]byte, error) {
	ret := _m.Called(method, url)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(method, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(method, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
